#!/bin/bash
#PBS -j oe
#PBS -N MEG_preproc
#PBS -q defaultQ
#PBS -l walltime=24:00:00
#PBS -o /headnode1/abry4213/github/Cogitate_Challenge_2024/preproc_CA103.out
#PBS -m abe
#PBS -M abry4213@uni.sydney.edu.au
#PBS -l select=1:ncpus=1:mem=20GB:mpiprocs=1
#PBS -V

#module load Anaconda3-5.1.0
/usr/physics/Modules/3.2.8/bin/modulecmd bash load Anaconda3-5.1.0 --silent
source /usr/physics/python/anaconda3/etc/profile.d/conda.sh 

# Activate conda environment
conda activate meg_msp1_env

# Call preprocessing script
MEG_repo_root=/headnode1/abry4213/github/cogitate-msp1/coglib
bids_root=/headnode1/abry4213/data/Cogitate_MEG_challenge
subject="CA103"
visit="1"
record="run"

# Freesurfer stuff
export FREESURFER_HOME=/headnode1/abry4213/software/freesurfer
export SUBJECTS_DIR=/headnode1/abry4213/data/Cogitate_MEG_challenge/derivatives/fs
export coreg_dir=/headnode1/abry4213/data/Cogitate_MEG_challenge/derivatives/coreg
export out_fw=/headnode1/abry4213/data/Cogitate_MEG_challenge/derivatives/forward

export PATH="$FREESURFER_HOME/bin:$PATH"
export PATH="$FREESURFER_HOME/fsfast/bin:$PATH"

#################################### Preprocessing ####################################
First do step 1
python3 $MEG_repo_root/meeg/preprocessing/P99_run_preproc.py \
--sub $subject --visit $visit --record $record --step 1 \
--bids_root $bids_root

# Then do step 2
python3 $MEG_repo_root/meeg/preprocessing/P99_run_preproc.py \
--sub $subject --visit $visit --record $record --step 2 \
--bids_root $bids_root

##################################### freesurfer ######################################

recon-all -all -subjid $subject -i /project/hctsa/annie/data/Cogitate_Batch1/MEG_Data/{$subject}/ses-1/anat/{$subject}_ses-1_T1w.nii.gz -sd /project/hctsa/annie/data/Cogitate_Batch1/MEG_Data/derivatives/fs

################################## Source modelling ###################################

# BEM
python3 $MEG_repo_root/meeg/source_modelling/S00_bem.py \
--sub $subject --visit $visit --bids_root $bids_root --fs_home $FREESURFER_HOME --subjects_dir $SUBJECTS_DIR

# Forward Model
python3 $MEG_repo_root/meeg/source_modelling/S01_forward_model.py \
--sub $subject --visit $visit --space surface --bids_root $bids_root --subjects_dir $SUBJECTS_DIR --coreg_path $coreg_dir --out_fw $out_fw

################################# Source localization #################################

# python3 $MEG_repo_root/meeg/activation/S01_source_loc.py \
# --sub $subject --visit $visit --method dspm \
# --bids_root $bids_root

# # Grand-average source localization for gamma band
# python3 $MEG_repo_root/meeg/activation/S02_source_loc_ga.py \
# --sub $subject --visit $visit --band gamma \
# --bids_root $bids_root
